//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berk_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class berk_siteEntities : DbContext
    {
        public berk_siteEntities()
            : base("name=berk_siteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategori> Kategoris { get; set; }
        public virtual DbSet<kullaniciadmin> kullaniciadmins { get; set; }
        public virtual DbSet<Makale> Makales { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
