//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berk_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullaniciadmin
    {
        public int id { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string sifre { get; set; }
        public string email { get; set; }
        public bool Aktif { get; set; }
        public bool sil { get; set; }
    }
}
