//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Berk_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makale
    {
        public int id { get; set; }
        public string MakaleBaslik { get; set; }
        public string MakaleOzet { get; set; }
        public string MakaleIcerik { get; set; }
        public string MakaleResim { get; set; }
        public Nullable<System.DateTime> MakaleTarih { get; set; }
        public Nullable<int> Sira { get; set; }
        public Nullable<int> makaleOkunma { get; set; }
        public Nullable<int> MakaleYorumSayisi { get; set; }
        public bool Aktif { get; set; }
        public int KategoriID { get; set; }
        public bool sil { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
